---
- name: Converge
  hosts: all
  become: true
  vars:
    stubby_service_state: started
    stubby_service_enabled: true
    stubby_config:
      upstream_recursive_servers:
        # Quad 9 'secure' service - Filters, does DNSSEC, doesn't send ECS
        - address_data: 9.9.9.9
          tls_auth_name: "dns.quad9.net"
        - address_data: 2620:fe::fe
          tls_auth_name: "dns.quad9.net"
  roles:
    - stubby
